//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace dotnet_inventory_example.Models
{
    using System;
    using System.Collections.Generic;
    using GridShared.DataAnnotations;

    public partial class Product2
    {
        public Product2()
        {
        }
        [Key]
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public string Description { get; set; }
        // public bool IsActive { get; set; }

        [NotMappedColumn]
        public virtual Units Unit { get; set; }
    }
}
